2024-12-10 01:31:24,869 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "d:\Games\Urban\Module_12\tests_12_4.py", line 24, in test_run
    run=rt_with_exceptions.Runner(["Burenka"])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Games\Urban\Module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано list
2024-12-10 01:31:24,876 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "d:\Games\Urban\Module_12\tests_12_4.py", line 12, in test_walk
    run=rt_with_exceptions.Runner("Milka",-5)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Games\Urban\Module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
